[package]
name = "count-nums"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.127"

#[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "counting"
harness = false
